name: watsonx.rescue_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.3
  - ibm-watson-machine-learning==1.0.338
  - ibm-cos-sdk==2.13.3
  - ibm-cloud-sdk-core==2.13.3
  - ibm-watson==7.01
  - openai==1.3.9
  - chromadb==0.4.15
  - plotly==5.18.0
  - chardet==5.2.0
  - langchain==0.1.5
  - langchain-experimental=0.0.50
  - pypdf
  - sentence_transformers==2.2.2
  - streamlit
  - fitz
  - pymupdf
  - spacy
  - beautifulsoup4
  - python-dotenv~=1.0.0
  - ragas==0.1.1
