MODEL_PROVIDER: WATSONX
OPENAI:
  ARTICLE_CLASSIFIER:
    decoding_method: GREEDY
    max_tokens: 1
    min_tokens: 1
    model_type: gpt-3.5-turbo-0301
    random_seed: null
    repetition_penalty: null
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: null
    top_p: null
    truncate_input_tokens: null
  EMBEDDINGS_COMPARATOR:
    decoding_method: GREEDY
    max_tokens: 300
    min_tokens: 50
    model_type: gpt-3.5-turbo-0301
    random_seed: null
    repetition_penalty: 1
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: 5
    top_p: 0.75
    truncate_input_tokens: null
  PREPROCESS_ARTICLE:
    decoding_method: GREEDY
    max_tokens: 500
    min_tokens: 20
    model_type: gpt-3.5-turbo-0301
    random_seed: null
    repetition_penalty: null
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: null
    top_p: null
    truncate_input_tokens: null
  TEXT_COMPARATOR:
    decoding_method: GREEDY
    max_tokens: 300
    min_tokens: 50
    model_type: gpt-3.5-turbo-0301
    random_seed: null
    repetition_penalty: 1
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: 5
    top_p: 0.75
    truncate_input_tokens: null
TASK: EMBEDDINGS_COMPARATOR
WATSONX:
  ARTICLE_CLASSIFIER:
    decoding_method: GREEDY
    max_tokens: 1
    min_tokens: 1
    model_type: FLAN_UL2
    random_seed: null
    repetition_penalty: null
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: null
    top_p: null
    truncate_input_tokens: null
  EMBEDDINGS_COMPARATOR:
    decoding_method: GREEDY
    max_tokens: 300
    min_tokens: 50
    model_type: LLAMA_2_13B_CHAT
    random_seed: null
    repetition_penalty: 1
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: 5
    top_p: 0.75
    truncate_input_tokens: null
  PREPROCESS_ARTICLE:
    decoding_method: SAMPLE
    max_tokens: 500
    min_tokens: 20
    model_type: FLAN_UL2
    random_seed: null
    repetition_penalty: 1
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: 4
    top_p: 0.75
    truncate_input_tokens: null
  TEXT_COMPARATOR:
    decoding_method: SAMPLE
    max_tokens: 300
    min_tokens: 0
    model_type: LLAMA_2_70B_CHAT
    random_seed: null
    repetition_penalty: 1
    return_options: null
    stop_sequences: null
    temperature: 0.0
    time_limit: null
    top_k: 4
    top_p: 1
    truncate_input_tokens: null
